version: '3.8'

services:
  device-orchestrator:
    image: device-orchestrator
    container_name: device-orchestrator
    build: .
    networks:
      - device-backend
    environment:
      CONSUL_HOST: consul
      MONGODB_URI: mongodb://device-orchestrator-mongo:27017/db
      MONGO_DB_HOST: device-orchestrator-mongo
      MONGO_DB_PORT: 27017
      MONGO_DB_USERNAME: app
      MONGO_DB_PASSWORD: pass
      MONGO_DB: db
    depends_on:
      - device-orchestrator-mongo
#      - consul

  device-orchestrator-mongo:
    image: mongo:3
    container_name: device-orchestrator-mongo
    expose:
      - "27017"
    networks:
      - device-backend
    environment:
      MONGO_INITDB_DATABASE: db
      MONGO_INITDB_ROOT_USERNAME: app
      MONGO_INITDB_ROOT_PASSWORD: pass
    volumes:
      - ./docker-entrypoint-initdb:/docker-entrypoint-initdb.d:ro

  consul:
    image: consul:1.8.3
    container_name: consul
    command: agent -dev -ui -node=server1 -bootstrap-expect=1 -client=0.0.0.0
    ports:
      - 8500:8500
    networks:
      - device-backend

networks:
  device-backend:
    external:
      name: device-backend