
spring:
  application:
    name: device-orchestrator
  cloud:
    consul:
      enabled: true
      service-registry:
        enabled: true
      discovery:
        register: true
      host: ${CONSUL_HOST:localhost}
      port: 8500
  data:
    mongodb:
      host: ${MONGO_DB_HOST:localhost}
      port: ${MONGO_DB_PORT:27017}
      database: ${MONGO_DB:db}
      username: ${MONGO_DB_USERNAME:app}
      password: ${MONGO_DB_PASSWORD:pass}
#      uri: ${MONGODB_URI:mongodb://localhost:27017/db}

security:
  oauth2:
    client:
      client-id: devicerenter
      client-secret: devicerentersecret
    resource:
      jwt:
        key-uri: http://localhost:7777/oauth/token_key