spring:
  application:
    name: device-orchestrator
  cloud:
    consul:
      enabled: true
      service-registry:
        enabled: true
      discovery:
        register: true
      host: ${CONSUL_HOST:localhost}
      port: 8500
  data:
    mongodb:
      uri: ${MONGODB_URI:mongodb://localhost:27017/db}
      username: ${MONGO_DB_USERNAME:app}
      password: ${MONGO_DB_PASSWORD:pass}
#      host: ${MONGO_DB_HOST:localhost}
#      port: ${MONGO_DB_PORT:27017}
#      database: ${MONGO_DB:db}

